sudo: false
dist: trusty
language: node_js
node_js:
- 8
addons:
  sauce_connect: true
before_script:
- export PATH=$PWD/node_modules/.bin:$PATH
- npm install -g nightwatch bower
- bower install
script:
- nightwatch --config nightwatch.conf.js --env chromesauce
